src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmployeRepository::class)
 */
class Employe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $service;

    /**
     * @ORM\Column(type="datetime")
     */
    private $EntryAt;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $salary;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getService(): ?string
    {
        return $this->service;
    }

    public function setService(string $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function getEntryAt(): ?\DateTimeInterface
    {
        return $this->EntryAt;
    }

    public function setEntryAt(\DateTimeInterface $EntryAt): self
    {
        $this->EntryAt = $EntryAt;

        return $this;
    }

    public function getSalary(): ?string
    {
        return $this->salary;
    }

    public function setSalary(string $salary): self
    {
        $this->salary = $salary;

        return $this;
    }
}

src/Form/EmployeFormType.php
<?php

namespace App\Form;

use App\Entity\Employe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class EmployeFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('firstname', TextType::class,[
            'label'=> 'Prénom'
        ])

        ->add('lastname', TextType::class,[
            'label'=> 'Nom'
        ])

        ->add('gender', TextType::class,[
            'label'=> 'Sexe'
        ])
        ->add('service',TextType::class,[
            'label' => 'Service'
        ])
        
        ->add('EntryAt', DateTimeType::class, array(
            'label' => 'Date'
        ))
        

        
        
        ->add('salary',TextType::class,[
            'label'=>'salaire'
        ])
        ->add('submit', SubmitType::class, [
            'label' => 'Valider',
            'validate' =>false

        ])
    ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Employe;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="default_home")
     */
    public function home(EntityManagerInterface $entityManger): Response

    {
        $employes = $entityManger ->getRepository(Employe::class)->findALL();
        return $this->render("default/home.html.twig",[
            "employes" => $employes
        ]);
    }
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;

use Requests;
use App\Entity\Employe;
use App\Form\EmployeFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;

class EmployeController extends AbstractController
{
    /**
     * @Route ("/ajouter-un-employe", name="employe_create", methods={"GET|POST"})
     */
    public function create (Request $request, EntityManagerInterface $entityManager ):Response
    {
        $employe = new Employe();

        $form = $this->createForm(EmployeFormType::class, $employe);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {

            //$form->get('salary')->getData();
            $entityManager->persist($employe);
            $entityManager->flush();
            
            return $this->redirectToRoute('default_home');

        }

        return $this->render("form/employe.html.twig", [
            "form_employe" => $form->createView()
        ]);

    }#end function create()


    /**
     * @Route("/modifier-un-employe-{id}", name="employe_update", methods={"GET|POST"})

     */
    public function update ( Employe $employe,Request $request, EntityManagerInterface $entityManager):Response
    {

        $form = $this->createForm(EmployeFormType::class, $employe)
        ->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $entityManager->persist($employe);
            $entityManager->flush();

            return $this->redirectToRoute('default_home');
        }
        return $this->render("form/employe.html.twig", [

            'employe'=>$employe,
            "form_employe" => $form->createView()
        ]);     
}

 /**
     * @Route("/supprimer-un-employe-{id}", name="employe_delete", methods={"GET"})

     */
public function delete(Employe $employe, EntityManagerInterface $entityManager): RedirectResponse
{
$entityManager->remove($employe);
$entityManager->flush();

return $this->redirectToRoute("default_home");

}


}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Entreprise{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet"
         href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">



        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    </head>
    <body>

    <header>
    
    {% include 'include/_nav.html.twig' %}

    </header>
        {% block body %} {% endblock %}
        <footer>
        
            {% include 'include/_footer.html.twig' %}

        </footer>

         {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>  
    </body>
</html>

templates/default/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page Accueil{% endblock %}

{% block body %}

<h1 class="text-center my-4">Bienvenue dans votre espace Admin</h1>
<div class="row">
        <div class="col-10 mx-auto">

            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Sexe</th>
                    <th>Service</th>
                    <th>Date d'embauche</th>
                    <th>Salaire</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for employe in employes %}
                    <tr>
                        <td>{{ employe.id }}</td>
                        <td>{{ employe.firstname }}</td>
                        <td>{{ employe.lastname }}</td>
                        <td>{{ employe.gender }}</td>
                        <td>{{ employe.service }}</td>
                        <td>{{ employe.entryAt | date('d/m/Y') }}</td>
                        <td>{{ employe.salary }}</td>
                        <td>
                            <a href="{{path('employe_update', {'id':employe.id} ) }}" class="btn btn-sm btn-primary" title="Modifier un employe"><i class="fa-solid fa-user-pen"></i></a>
                            <a href="{{path('employe_delete', {'id':employe.id} ) }}" class="btn btn-sm btn-danger" title="Supprimer un employe"><i class="fa-solid fa-trash"></i></a>
                        </td>
                    </tr>
                {%  endfor %}
                </tbody>
            </table>

        </div>
    </div>




 


{% endblock %}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EmployeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/mast-/OneDrive/Documents/doranco/Symfony/Entreprise/src/Controller/EmployeController.php'|file_link(0) }}">src/Controller/EmployeController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/mast-/OneDrive/Documents/doranco/Symfony/Entreprise/templates/employe/index.html.twig'|file_link(0) }}">templates/employe/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/form/employe.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un employé{% endblock %}

{% block body %}


{% if employe is not defined %}

    <h1 class="text-center my-4">Ajout d'un nouvel employé</h1>

{% else %}

      <h1 class="text-center my-4">Modifier l'empolyé {{employe.firstname}} {{employe.lastname}}</h1>
{% endif %}

<div class="row">
    <div class="col-8 mx-auto">

       {#{{ form (form_employe) }}#}

       {# Pour désactiver le validateur HTML coté-client (navigateur) on peut le faire 
            dans EmployeFormType ('submit') OU dans le form_start en second argument comme suit: #}


        {{ form_start(form_employe,{'attr': {novalidate: 'novalidate'}}
) }}

         {{ form_row(form_employe.lastname) }}
        {{ form_row(form_employe.firstname) }}

        {{ form_end(form_employe)}}

        <div class="row">
        {# <div class="col-6"> {{ form_row(form_employe.service) }}</div> #}
        {# <div class="col-6"> {{ form_row(form_employe.salary) }}</div> #}
        </div>
         {# {{ form_row(form_employe.gender) }} #}
          {# {{ form_row(form_employe.entryAt) }} #}
    </div>
</div>


{% endblock %}

templates/include/_footer.html.twig
{# ////////////////////////////////// FIRST PART //////////////////////////////////// #}
    <div class="container border-top">
        <div class="row mt-3">
            <div class="col-12 col-md">
                <h5>Employes</h5>
                <small class="d-block text-muted">&copy; {{ "now"|date('Y') }}</small>
            </div>
            <div class="col-6 col-md">
                <ul class="list-unstyled">
                    <li><a href="#" class="text-muted">Mentions légales</a></li>
                    <li><a href="#" class="text-muted">Politique de confidentialité</a></li>
                    <li><a href="#" class="text-muted">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>

{# ////////////////////////////////// SECOND PART //////////////////////////////////// #}
    <div class="container-fluid bg-dark mt-5">
        <p class="text-center text-white p-2 m-0">
            &copy; Entreprise {{ "now"|date('Y') }} - Made with ❤ by
            <a href="https://github.com/mastfel"
               target="_blank"
               class="text-reset"
               data-bs-toggle="tooltip"
               data-bs-placement="right"
               data-bs-html="true"
               title="Have a look to my GitHub <i class='fa-brands fa-github'></i>"
            >Prenom Nom</a>
        </p>
    </div>

templates/include/_nav.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Entreprise</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ path('default_home') }}">Accueil</a>
        </li>
        

       <li class="nav-item">
          <a class="nav-link" href="{{ path('employe_create') }}">Ajouter un employé</a>
        </li>
        
          
       
      </ul>
      
    </div>
  </div>
</nav>